export const contactList = [
  {
    id: 1,
    name: "Maya Kasuma",
    profilePic: "https://picsum.photos/id/1011/200/200",
    lastText: "Yes Ok!",
    lastTextTime: "12:58 PM",
  },
  {
    id: 2,
    name: "Steve Ballmer",
    profilePic: "https://picsum.photos/id/1012/200/200",
    lastText: "Developer, developers ,develop...",
    lastTextTime: "12:45 PM",
  },
  {
    id: 3,
    name: "Stasa Benko",
    profilePic: "https://picsum.photos/id/1027/200/200",
    lastText: "Call me when you can",
    lastTextTime: "12:30 PM",
  },
  {
    id: 4,
    name: "Gaurav Singh",
    profilePic: "https://picsum.photos/id/870/200/200?grayscale&blur=2",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 5,
    name: "Alice Whitman",
    profilePic: "https://picsum.photos/200",
    lastText: "Yes that's my fave too!",
    lastTextTime: "12:00 PM",
  },
  {
    id: 6,
    name: "John Appleseed",
    profilePic: "https://picsum.photos/seed/picsum/200/200",
    lastText: `I'm with Gaurav`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 7,
    name: "Elon Bezoz",
    profilePic: "https://picsum.photos/id/1004/200/200",
    lastText: "Where is my Tesla?",
    lastTextTime: "12:30 PM",
  },
  {
    id: 8,
    name: "Jeff Musk",
    profilePic: "/jeff.jpeg",
    lastText: "Travelling to space",
    lastTextTime: "12:00 PM",
  },
];
export const messagesList = [
  {
    id: 1,
    messageType: "TEXT",
    text: "Hey Man 😁",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 2,
    messageType: "TEXT",
    text: "Hey, What's up?",
    senderID: 1,
    addedOn: "12:01 PM",
  },
  {
    id: 3,
    messageType: "TEXT",
    text: "All Good, What about you?",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 4,
    messageType: "TEXT",
    text: "I'm good as well",
    senderID: 1,
    addedOn: "12:00 PM",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "Great 😁",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "Have you subscribed The Indian Dev ?",
    senderID: 1,
    addedOn: "12:00 PM",
  },
];
